### ISSUE TITLE
Wordpress link removal, template latex

### ISSUE THREAD

**Issue by medusamedusa** [isqcmc/isqcmc2025#10]
Hi! We can remove the link toward the Wordpress page, as I made it private. We can add a link toward the conference correct template. Then, I think we can share the link with Prof. Miranda and Moth for sharing.

**Comment by medusamedusa** [comment]
Yes, the link was only there.On 5 Nov 2024, at 19:23, OCH ***@***.***> wrote:﻿
@medusamedusa
please see #11
It was only at the bottom, right?

**Comment by omarcostahamido** [comment]
it's ready to approve to merge, then
