### ISSUE TITLE
add good old ISQCMC font

### ISSUE THREAD

**Issue by omarcostahamido** [isqcmc/isqcmc2025#4]
i know it looks a bit funny, but there's a font for isqcmc that has been part of the last 2 editions of the conference and earned some consistency.
@medusamedusa do you want to take on updating conference logo using this same font?
it's called Glory, and you can see how it was fetched for 2021:
https://github.com/isqcmc/isqcmc2021/blob/gh-pages/newslate.css
`@import url("https://fonts.googleapis.com/css2?family=Glory:wght@800&display=swap");`
and then used in context:
https://github.com/isqcmc/isqcmc2021/blob/gh-pages/_layouts/default.html

**Comment by medusamedusa** [comment]
Yes, I can include the font to write down the name; the logo is the one with the triskelion and the atom.

**Comment by omarcostahamido** [comment]
here the font to download from google fonts:
https://fonts.google.com/specimen/Glory?preview.text=ISQCMC&query=glory
used `bold` or weight `700`.
Thanks!

**Comment by omarcostahamido** [comment]
besides potentially including it in the logo, this is what i was thinking as well:
<img width="861" alt="Screenshot 2024-10-17 at 1 19 05 PM" src="https://github.com/user-attachments/assets/fd4e5fed-11f9-496a-8dd7-ee9a687ce157">

**Comment by omarcostahamido** [comment]
> besides potentially including it in the logo, this is what i was thinking as well:
> <img width="861" alt="Screenshot 2024-10-17 at 1 19 05 PM" src="https://github.com/user-attachments/assets/fd4e5fed-11f9-496a-8dd7-ee9a687ce157">

_bump_
shall we at least bring this good old font back?

**Comment by omarcostahamido** [comment]
@medusamedusa 
I just got started on this, and added the font to the `ISQCMC '25` header like i showed on the picture above.
it is on the [`isqcmcfont`](https://github.com/isqcmc/isqcmc2025/tree/isqcmcfont) branch, and it has an open `draft` pull request for it as #9 .
I set it as draft as I am not sure it solves all the things brought up in this issue. Do you wanted to remake the image as well?
Feel free to change your local clone to `isqcmcfont` branch and add and push your own changes.

**Comment by omarcostahamido** [comment]
merged `isqcmcfont`.
if you want to work on a new logo then keep this issue open, else also feel free to close it.

**Comment by medusamedusa** [comment]
Thanks! To avoid providing LaTeX codes for now, we can just substitute

“Standard article template, 5 pages”

To the current

 Springer LNCS <https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines> format

**Comment by omarcostahamido** [comment]
I think you meant to write this on issue #6 not here, this issue #4 is closed already.

**Comment by medusamedusa** [comment]
Yes, thank you :)
