### ISSUE TITLE
paper template

### ISSUE THREAD

**Issue by omarcostahamido** [isqcmc/isqcmc2025#6]
i noticed that @medusamedusa wrote on the initial page that participants should use the lncs springer template.
me and mostly @Itaborala did work on a isqcmc template which is still downloadable on the [indico page](https://indico.desy.de/event/38609/overview).
Should this still be considered, or just let it be as it is?

**Comment by medusamedusa** [comment]
We can keep the template we used before, of course!

Can you please let me know how can I reply to the comments directly on GitHub? :)

**Comment by omarcostahamido** [comment]
> Can you please let me know how can I reply to the comments directly on GitHub? :)

at the bottom of the email there is a link to the issue or pull request in question.
you can click it, log in to github and reply there as well :)

**Comment by omarcostahamido** [comment]
just to note the cross-post: https://github.com/isqcmc/isqcmc.github.io/issues/5

**Comment by omarcostahamido** [comment]
@medusamedusa wrote https://github.com/isqcmc/isqcmc2025/issues/4#issuecomment-2480494875 
> Thanks! To avoid providing LaTeX codes for now, we can just substitute
“Standard article template, 5 pages”
To the current
 Springer LNCS <https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines> format

I am not sure I understand that.
Currently is it already saying: Springer LNCS <https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines> format
Did you mean to say to replace that with: “Standard article template, 5 pages”
?

**Comment by medusamedusa** [comment]
Yes, because the proceedings will not be published by Springer. (Maybe the post-conference book).
I’m open to suggestions; I just wanted a standard .tex template, we do not have to provide.

**Comment by omarcostahamido** [comment]
got it. 
on it.
