### ISSUE TITLE
Updating Committee on the website

### ISSUE THREAD

**Issue by Itaborala** [isqcmc/isqcmc2025#7]
After the discussions regarding the advisory board, we need to update the website.

One idea discussed with @medusamedusa is to have the Peer-review committe to be displayed in a separate page, or somehow being part of a box that expands when someone clicks in it. More Ideas @omarcostahamido ?

In any case, I believe we are already safe to update the advisory board and include the organizers to the homepage?

**Comment by omarcostahamido** [comment]
> One idea discussed with @medusamedusa is to have the Peer-review committe to be displayed in a separate page, or somehow being part of a box that expands when someone clicks in it. More Ideas @omarcostahamido ?

It can be a separate page, or it can be a popup modal box, or maybe even an accordion/foldable menu. I'd reckon all credits should stay relatively together, but in order to simplify space being used we can use one of the later 2 options. I can try to explore the last one, since a modal with a big list might not work well on mobile.
I'll open a branch to explore that. Can you give me the updated list?

**Comment by omarcostahamido** [comment]
@Itaborala @medusamedusa PR #8 ready for review

**Comment by medusamedusa** [comment]
Thank you! We should add
Florian Carle (Yale University, USA)

**Comment by medusamedusa** [comment]
How can I visualize the modified webpage, also from GitHub desktop? Sorry, I have forgotten something :)

**Comment by medusamedusa** [comment]
And now the Wordpress site is private :)
—Maria

**Comment by omarcostahamido** [comment]
@medusamedusa 

> Thank you! We should add
Florian Carle (Yale University, USA)

added.

> How can I visualize the modified webpage, also from GitHub desktop? Sorry, I have forgotten something :)

No worries.
Yes, 
- open github desktop
- fetch last changes (third button/tab on top)
- change to `updtcommittee` branch (second button/tab on top)
- this changes the files to what they look like on this branch, and you can see that when you open the folder on finder :)
- now either click and open the `index.html` file or, better yet, start a local server to serve the files like a real server
  - open terminal
  - navigate to repository folder
  - run `ws` (*assuming you have [local-web-server](https://www.npmjs.com/package/local-web-server) still installed)
  - then open a browser window and navigate to `http://localhost:8000`

**Comment by medusamedusa** [comment]
Super, thanks!

(I had forgotten to open the folder on finder ;)
